### ISSUE TITLE
Decode token in Android

### ISSUE THREAD

**Issue by EzequielMonteleone** [blake-simpson/expo-jwt#13]
Hi Guys.. i am working in a app with React Native using Expo.. I have an error and it only happen in Android(it doesn't always), in iOS work fine, and i don't know what es the reason. the error is: 

Issued At claim is invalid
* [native code]:null in construct
* http://192.168.0.57:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:160756:86 in IssuedAtInvalid
- node_modules/expo-jwt/dist/verifier.js:85:6 in verify_iat
- node_modules/expo-jwt/dist/verifier.js:46:28 in Verifier
- node_modules/expo-jwt/dist/verifier.js:32:13 in verifyAll
* [native code]:null in forEach
* http://192.168.0.57:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:161706:23 in verifyAll
- node_modules/expo-jwt/dist/decoder.js:93:35 in verifyClaims
* http://192.168.0.57:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:161608:26 in decodeAndVerify
* src/views/logInScreen.tsx:169:26 in loginAsync
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:274:30 in invoke
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:135:28 in invoke
- node_modules/regenerator-runtime/runtime.js:145:19 in PromiseImpl.resolve.then$argument_0
- node_modules/promise/setimmediate/core.js:37:14 in tryCallOne
- node_modules/promise/setimmediate/core.js:123:25 in setImmediate$argument_0
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:146:14 in _callTimer
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:194:17 in _callImmediatesPass
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:458:30 in callImmediates
* [native code]:null in callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:407:6 in __callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:143:6 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:384:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:142:17 in __guard$argument_0
* [native code]:null in flushedQueue
* [native code]:null in invokeCallbackAndReturnFlushedQueue

Any idea?
Thanks

**Comment by blake-simpson** [comment]
Hi @EzequielMonteleone,

Do you have an example of the JWT token that you are trying to decode?

Have you checked the system time vs the `iat` time set i the token to prove that `iat` is not in the past? If this is the case you may want to try passing the `timeSkew` option to see if it helps?

For an example, please see the following issue: https://github.com/kartenmacherei/expo-jwt/issues/7#issuecomment-537567431

**Comment by EzequielMonteleone** [comment]
Blake, Yes was the timeSkew.. it work now, thanks very much
