### ISSUE TITLE
possibility to add an expiration time to the generated token

### ISSUE THREAD

**Issue by potier97** [blake-simpson/expo-jwt#17]
Hello, I am using this library and I would like to know if there is the possibility of adding a new feature to it, which is the lifetime of the token generated by the user, as it happens in the JSONWEBTOKEN library for node, thanks

**Comment by blake-simpson** [comment]
Hi @potier97,

This library will automatically check the expiration time of the JWT if there is an `exp` key in the encoded payload, while decoding.

For example on encoding with expiration:

```
const key = 'secret';
const token = JWT.encode({ foo: 'bar', exp:  1609361060218 }, key);
```

If you then run the decoder and the `exp` time is less than the current time, the library will throw the exception `TokenExpired`.

An example of decoding would simply be this, as the `exp` is automatically checked if present in the payload.

```
try {
  const body = JWT.decode(token, key);
} catch (error) {
  // if the token has expired the error here will be `TokenExpired`.
}
```

**Comment by potier97** [comment]
Hi @blake-simpson, I understand, thanks for your explanation, then I can close this thread

Thanks.
