### ISSUE TITLE
Issued At claim is invalid when using the expo-jwt

### ISSUE THREAD

**Issue by Hulker** [blake-simpson/expo-jwt#28]
Hello,
I'm getting "Issued At claim is invalid" when using  the expo decode function 
the iat is not in the past and I event tried to add the { timeSkew: 30 } and it still not working 

var decodedHeader = JWT.decode(tokenvar, key, { timeSkew: 30 });

![image](https://user-images.githubusercontent.com/4717149/209655555-bd6cac60-182c-4611-acef-c358aaca2ff6.png)

Thanks!!!!

**Comment by blake-simpson** [comment]
Hi @Hulker, sorry for the slow response.

Were you able to solve the issue?

From what I see here, it would be good to know what the timestamp was at the time you tried to validate this payload.
Perhaps you need a large `timeSkew` than 30?

**Comment by Hulker** [comment]
Hi @blake-simpson  :-)
Thank you for your response.

It seems to work now without me doing anything that I'm aware of :-)
var decodedHeader = JWT.decode(tokenvar, key, { timeSkew: 30 });

Thanks again.

Best,
