### ISSUE TITLE
JWT Expired validation error

### ISSUE THREAD

**Issue by cfanboy** [blake-simpson/expo-jwt#3]
Hi there,

Out JWT expired date is based on seconds, but we found the expo-jwt only supported the millisecond to be valid, or else it's expired.
If possible to add a configure parameter to indicate which unit to be used.
Thanks

**Comment by blake-simpson** [comment]
Hey,

You are correct, the RFC states 
> A JSON numeric value representing the number of seconds from
      1970-01-01T00:00:00Z UTC until the specified UTC date/time,
      ignoring leap seconds.

https://tools.ietf.org/html/rfc7519#section-2

I would change `expo-jwt` to use seconds instead of milliseconds in general. If you have a PR, feel free, otherwise I would plan to work on this soon.

**Comment by cfanboy** [comment]
Sent PR request

**Comment by blake-simpson** [comment]
v1.1.0 was just released to NPM
