### ISSUE TITLE
Token must be in the format: header.body.signature

### ISSUE THREAD

**Issue by anangkf** [blake-simpson/expo-jwt#30]
Hi, I am working on React Native Expo app. I tried to decode JWT using this expo-jwt library but getting `Error: Token must be in the format: header.body.signature`

here is my example jwt token:
```eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMWI2OGIwZC01NWM4LTQ5NGEtODcxMS0yNzliOTIyZDQ3NzMiLCJlbWFpbCI6InRlc3RAbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTY4NDA1MTY4NiwiZXhwIjoxNjg0MTM4MDg2fQ.jSp-Xtx7Ru9i8NCdC91Su6D0RjZzf-_uzsw1q0trUmw```

and this is how my code:
```typescript
const getRole = (accessToken: string): string => {
    const decoded = JWT.decode(accessToken, CONST.JWT_SECRET); //this cause the error
    //rest logic
    return decoded.role;
};
``` 

any idea?

**Comment by blake-simpson** [comment]
Hi @anangkf 

Are you sure that the token is in this format, as a string?

The lib splits the string on the `.` character to get the header, body, and signature: https://github.com/blake-simpson/expo-jwt/blob/master/lib/decoder.ts#L85

Is the `accessToken` you are passing encoded by chance?

**Comment by anangkf** [comment]
I am not sure. 
I actually store the jwt token  from API to the SharedPrefs using `AsyncStorage`.
here is how I get the token from SharedPrefs:
```typescript
const getToken = async (): Promise<string | null> => {
    const accessToken = await AsyncStorage.getItem('accessToken');
    return accessToken;
  };
```
I log the token I get from the `getToken` function then the console show the token above.

**Comment by blake-simpson** [comment]
Are you using `await` when you call `getToken`? Otherwise you would get a promise back instead of the resolved promise value. 

Perhaps you can share a little more of the files affected?

**Comment by anangkf** [comment]
finally I got what I need. but I still dont know what's wrong in the past

```typescript
const getToken = async (): Promise<string | null> => {
    const accessToken = await AsyncStorage.getItem('accessToken'); // eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1M2JlMWQwYy0yZmZjLTQyMDUtODViOC1kM2I3OTkwNjMwOGEiLCJlbWFpbCI6InN1cGVyYWRtaW5AbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODQzMzExMjMsImV4cCI6MTY4NDQxNzUyM30.2pNKO1sInxEvYjLq4CkZpg7JAaqvVQQi988n050rbRw
    return accessToken;
  };

const getRole = (accessToken: string): string | null => {
    const { role } = JWT.decode(accessToken, CONST.JWT_SECRET); // 'user' | 'admin'
    return role;
  };

const determineAuthStatus = async (): Promise<boolean> => {
    const accessToken = await getToken();
    setIsLoggedIn(Boolean(accessToken));

    if(accessToken) {
      const role = getRole(accessToken as string);
      setRole(role);
    }
    return Boolean(accessToken);
  };
```

thanks @blake-simpson for any advice :)

**Comment by blake-simpson** [comment]
Im glad you got the issue resolved!
