### ISSUE TITLE
Decode JWT without a key in TS

### ISSUE THREAD

**Issue by teddybee** [blake-simpson/expo-jwt#36]
I have token authentication in my Expo app. I need only a simple token decode without a key. 
How can I do that in typescript?

**Comment by blake-simpson** [comment]
Hi, do you have an example of the token in question?

By no key, I assume you mean that no encryption algorithm was used to encode the JWT? In which case, you can try to set the `algorithm` option to `none` when decoding:

```ts
const myToken = 'my.token.';
const key = null;

const decodedValue = JWT.decode(myToken, key, { algorithm: 'none' });
```

**Comment by teddybee** [comment]
Yes, the token has no key.
Thank you this solution is working. 
Although the TS compiler or linter doesn't like the null key. Also the algorithm option does not exist in TS declaration.
```
You can't pass property algorithm to type DecodingOptions
```

**Comment by blake-simpson** [comment]
Good point, this wasn't an expected use case but it should be. Could you please use a `// @ts-ignore` for now please and I will update the types and release a version for you.

**Comment by blake-simpson** [comment]
I've just released [1.7.0](https://www.npmjs.com/package/expo-jwt/v/1.7.0) for you that should address this. I've made this test file and it's compiling for me. Perhaps you can confirm after trying out the update please?

Note: You should also import `SupportedAlgorithms` and use the enum value `NONE` for the algorithm options too.

```ts
import JWT, { SupportedAlgorithms } from 'expo-jwt';

const token = 'my.token.';
const key = null;

JWT.decode(token, key, { algorithm: SupportedAlgorithms.NONE });
```

**Comment by teddybee** [comment]
Thank you for the help.
Template literals could be worked as well in TS(just a suggestion). 
```
const SupportedAlgorithms = {
  NONE: 'none',
  OTHER: 'OTHER',
} as const;
type Algorithm= typeof SupportedAlgorithms [keyof typeof SupportedAlgorithms];
````

**Comment by blake-simpson** [comment]
I tried something like that but I think it's better not to mix up strings with enums if possible. If people report it's painful we can drop the enum entirely and make a union string... would importing `SupportedAlgorithms` be ok for now though?

**Comment by teddybee** [comment]
Of course its good as well.

**Comment by blake-simpson** [comment]
Ok, thanks for reporting this! I'll close the issue for now. If you have any more issues in the future just ask away :)
