### ISSUE TITLE
JWTBody type is incorrect

### ISSUE THREAD

**Issue by dPreininger** [blake-simpson/expo-jwt#37]
You define JWTBody as:

```
export type JWTBody<T = any> = Record<string, T>;
```

If we take a look what your docs say: 
```
const foo = JWT.decode(token, key);
// foo.body === any

type MyType = Record<string, number>;
const bar = JWT.decode<MyType>(token, key);
// bar.body === MyType
```
Which is obviously incorrect.

`foo.body` is of type `Record<string, any>`, not `any`.
`bar.body` is of type `Record<string, MyType>` (if we expand this further we get `Record<string, Record<string, number>>`) not `MyType`.

If you are not adept at TypeScript, I suggest looking at jwt-decode library source and how they did types there.

**Comment by blake-simpson** [comment]
Ouch 😅

Yes, there is a mistake. Thank you for reporting it. 
This is the beauty of Open Source. We can all work together to review code and fix mistakes!
Perhaps you would like to make a PR to help fix this issue?

**Comment by dPreininger** [comment]
Sure, coming right up.

**Comment by dPreininger** [comment]
#38 is ready for review.
